services:
  backend:
    build: ./backend
    networks:
      - chatnet

  frontend:
    build: ./frontend
    networks:
      - chatnet

  nginx:
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - chatnet

networks:
  chatnet:
